//! Resource flow and automation logic

use super::{Grid, GridPos};
use macroquad_toolkit::grid::bfs_path as toolkit_bfs_path;
use serde::{Deserialize, Serialize};

/// Resource types that can be gathered and transported
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResourceType {
    Minerals,
    Energy,
    Data,
    Biomass,
}

/// Drone states for the automation system
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DroneState {
    Idle,          // Waiting at drill
    MovingToCore,  // Carrying resources to Core
    MovingToDrill, // Returning to drill
    Delivering,    // Unloading at Core
    Error,         // Path blocked or other issue
}

/// Represents a drone carrying resources
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Drone {
    pub id: u32,
    pub position: GridPos,
    pub target: GridPos,
    pub home_drill: GridPos,
    pub state: DroneState,
    pub resource_type: ResourceType,
    pub carrying: f32,
    pub capacity: f32,
    pub speed: f32,
    pub progress: f32, // 0.0 to 1.0 for smooth movement
    pub path: Vec<GridPos>,
    pub path_index: usize,
}

impl Drone {
    pub fn new(id: u32, drill_pos: GridPos, capacity: f32, speed: f32) -> Self {
        Self {
            id,
            position: drill_pos,
            target: drill_pos,
            home_drill: drill_pos,
            state: DroneState::Idle,
            resource_type: ResourceType::Minerals,
            carrying: 0.0,
            capacity,
            speed,
            progress: 0.0,
            path: Vec::new(),
            path_index: 0,
        }
    }

    /// Start moving to Core with resources
    pub fn dispatch_to_core(&mut self, core_pos: GridPos, path: Vec<GridPos>, amount: f32) {
        self.target = core_pos;
        self.carrying = amount.min(self.capacity);
        self.state = DroneState::MovingToCore;
        self.path = path;
        self.path_index = 0;
        self.progress = 0.0;
    }

    /// Start returning to drill
    pub fn return_to_drill(&mut self, path: Vec<GridPos>) {
        self.target = self.home_drill;
        self.carrying = 0.0;
        self.state = DroneState::MovingToDrill;
        self.path = path;
        self.path_index = 0;
        self.progress = 0.0;
    }

    /// Update drone position and state
    pub fn update(&mut self, delta_time: f32) -> Option<DroneEvent> {
        match self.state {
            DroneState::Idle => None,
            DroneState::MovingToCore | DroneState::MovingToDrill => {
                self.progress += self.speed * delta_time;

                if self.progress >= 1.0 {
                    self.progress = 0.0;
                    self.path_index += 1;

                    if self.path_index >= self.path.len() {
                        // Reached destination
                        self.position = self.target;
                        if self.state == DroneState::MovingToCore {
                            self.state = DroneState::Delivering;
                            return Some(DroneEvent::ReachedCore {
                                drone_id: self.id,
                                amount: self.carrying,
                            });
                        } else {
                            self.state = DroneState::Idle;
                            return Some(DroneEvent::ReachedDrill { drone_id: self.id });
                        }
                    } else {
                        self.position = self.path[self.path_index];
                    }
                }
                None
            }
            DroneState::Delivering => {
                // Delivery happens instantly for now
                self.state = DroneState::Idle;
                None
            }
            DroneState::Error => None,
        }
    }

    /// Get interpolated visual position for smooth rendering
    pub fn visual_position(&self) -> (f32, f32) {
        if self.path_index < self.path.len() && self.path_index > 0 {
            let from = self.path[self.path_index - 1];
            let to = self.path[self.path_index];
            let interp_x = from.x as f32 + (to.x - from.x) as f32 * self.progress;
            let interp_y = from.y as f32 + (to.y - from.y) as f32 * self.progress;
            (interp_x, interp_y)
        } else {
            (self.position.x as f32, self.position.y as f32)
        }
    }
}

/// Events generated by drone actions
#[derive(Debug, Clone)]
pub enum DroneEvent {
    ReachedCore { drone_id: u32, amount: f32 },
    ReachedDrill { drone_id: u32 },
    PathBlocked { drone_id: u32 },
}

/// Manages all drones in the game
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DroneManager {
    drones: Vec<Drone>,
    next_id: u32,
    pub drone_capacity: f32,
    pub drone_speed: f32,
}

impl DroneManager {
    pub fn new(capacity: f32, speed: f32) -> Self {
        Self {
            drones: Vec::new(),
            next_id: 1,
            drone_capacity: capacity,
            drone_speed: speed,
        }
    }

    /// Spawn a new drone at a drill position
    pub fn spawn_drone(&mut self, drill_pos: GridPos) -> u32 {
        let id = self.next_id;
        self.next_id += 1;
        self.drones.push(Drone::new(
            id,
            drill_pos,
            self.drone_capacity,
            self.drone_speed,
        ));
        id
    }

    /// Get all drones
    pub fn drones(&self) -> &[Drone] {
        &self.drones
    }

    /// Get mutable access to drones
    pub fn drones_mut(&mut self) -> &mut [Drone] {
        &mut self.drones
    }

    /// Get mutable reference to a drone by ID
    pub fn get_drone_mut(&mut self, id: u32) -> Option<&mut Drone> {
        self.drones.iter_mut().find(|d| d.id == id)
    }

    /// Get drones at a specific drill
    pub fn drones_at_drill(&self, drill_pos: GridPos) -> Vec<&Drone> {
        self.drones
            .iter()
            .filter(|d| d.home_drill == drill_pos)
            .collect()
    }

    /// Remove all drones assigned to a specific drill
    pub fn remove_drones_at_drill(&mut self, drill_pos: GridPos) {
        self.drones.retain(|drone| drone.home_drill != drill_pos);
    }

    /// Get idle drones at a specific drill
    pub fn idle_drones_at_drill(&mut self, drill_pos: GridPos) -> Vec<&mut Drone> {
        self.drones
            .iter_mut()
            .filter(|d| d.home_drill == drill_pos && d.state == DroneState::Idle)
            .collect()
    }

    /// Update all drones and return events
    pub fn update(&mut self, delta_time: f32) -> Vec<DroneEvent> {
        let mut events = Vec::new();
        for drone in &mut self.drones {
            if let Some(event) = drone.update(delta_time) {
                events.push(event);
            }
        }
        events
    }

    /// Count drones by state
    pub fn count_by_state(&self, state: DroneState) -> usize {
        self.drones.iter().filter(|d| d.state == state).count()
    }

    /// Total number of drones
    pub fn total_count(&self) -> usize {
        self.drones.len()
    }
}

/// Simple pathfinding - returns direct path (no obstacle avoidance yet)
pub fn find_path(grid: &Grid, from: GridPos, to: GridPos) -> Vec<GridPos> {
    if from == to {
        return Vec::new();
    }

    let passable = |pos: GridPos, grid: &Grid| {
        if let Some(tile) = grid.get(pos) {
            !matches!(
                tile.terrain,
                super::TerrainType::Void | super::TerrainType::Water
            ) || tile.bridge
        } else {
            false
        }
    };

    if let Some(path) = toolkit_bfs_path(
        from.to_tile_pos(),
        to.to_tile_pos(),
        false,
        |pos| GridPos::from_tile_pos(pos).in_bounds(grid.width, grid.height),
        |pos| passable(GridPos::from_tile_pos(pos), grid),
    ) {
        return path
            .into_iter()
            .skip(1)
            .map(GridPos::from_tile_pos)
            .collect();
    }

    // Fallback to direct path if BFS fails.
    let mut path = Vec::new();
    let mut current = from;
    while current.x != to.x {
        current.x += if current.x < to.x { 1 } else { -1 };
        path.push(current);
    }
    while current.y != to.y {
        current.y += if current.y < to.y { 1 } else { -1 };
        path.push(current);
    }
    path
}
